config/routes.rb
Rails.application.routes.draw do
  resources :entries
  resources :budgets

  root 'budgets#index'

end

app/models/budget.rb
class Budget < ActiveRecord::Base
  has_many :entries, :dependent => :delete_all
  validates :balance, :presence => true

  def get_budget_total
  	if self.balance
      newtotal = balance
        entries.each do |entry|
          newtotal += entry.amount
        end
      newtotal
    end
  end
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :budget
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/budgets_controller.rb
class BudgetsController < ApplicationController
  before_action :set_budget, only: [:show, :edit, :update, :destroy]

  # GET /budgets
  # GET /budgets.json
  def index
    @budgets = Budget.all
  end

  # GET /budgets/1
  # GET /budgets/1.json
  def show
    @entry = Entry.new
  end

  # GET /budgets/new
  def new
    @budget = Budget.new
  end

  # GET /budgets/1/edit
  def edit
  end

  # POST /budgets
  # POST /budgets.json
  def create
    @budget = Budget.new(budget_params)

    respond_to do |format|
      if @budget.save
        format.html { redirect_to @budget, notice: 'Budget was successfully created.' }
        format.json { render :show, status: :created, location: @budget }
      else
        format.html { render :new }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /budgets/1
  # PATCH/PUT /budgets/1.json
  def update
    respond_to do |format|
      if @budget.update(budget_params)
        format.html { redirect_to @budget, notice: 'Budget was successfully updated.' }
        format.json { render :show, status: :ok, location: @budget }
      else
        format.html { render :edit }
        format.json { render json: @budget.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /budgets/1
  # DELETE /budgets/1.json
  def destroy
    @budget.destroy
    respond_to do |format|
      format.html { redirect_to budgets_url, notice: 'Budget was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_budget
      @budget = Budget.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def budget_params
      params.require(:budget).permit(:name, :description, :balance)
    end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update, :destroy]

  # GET /entries
  # GET /entries.json
  def index
    @entries = Entry.all
  end

  # GET /entries/1
  # GET /entries/1.json
  def show
  end

  # GET /entries/new
  def new
    @entry = Entry.new
  end

  # GET /entries/1/edit
  def edit
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)
    @budget = Budget.find(@entry.budget_id)

    respond_to do |format|
      if @entry.save
        format.html { redirect_to @budget, notice: 'Entry was successfully created.' }
        format.json { render :show, status: :created, location: @entry }
      else
        format.html { render :new }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    respond_to do |format|
      if @entry.update(entry_params)
        format.html { redirect_to @entry, notice: 'Entry was successfully updated.' }
        format.json { render :show, status: :ok, location: @entry }
      else
        format.html { render :edit }
        format.json { render json: @entry.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entries/1
  # DELETE /entries/1.json
  def destroy
    @entry.destroy
    respond_to do |format|
      format.html { redirect_to entries_url, notice: 'Entry was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_entry
      @entry = Entry.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def entry_params
      params.require(:entry).permit(:amount, :description, :budget_id, :deductible)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/budgets_helper.rb
module BudgetsHelper
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/budgets/_form.html.erb
<%= form_for(@budget) do |f| %>
  <% if @budget.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@budget.errors.count, "error") %> prohibited this budget from being saved:</h2>

      <ul>
      <% @budget.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label "Starting Balance" %><br>
    <%= f.text_field :balance %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/budgets/edit.html.erb
<h1>Editing Budget</h1>

<%= render 'form' %>

<%= link_to 'Show', @budget %> |
<%= link_to 'Back', budgets_path %>

app/views/budgets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Budgets</h1>

<table class="gridtable">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Starting Balance</th>
      <th>Running Balance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @budgets.each do |budget| %>
      <tr>
        <td><%= budget.name %></td>
        <td><%= budget.description %></td>
        <td><%= number_to_currency(budget.balance) %></td>
        <td><%= number_to_currency(budget.get_budget_total) %></td>
        <td><%= link_to 'Show', budget %></td>
        <td><%= link_to 'Edit', edit_budget_path(budget) %></td>
        <td><%= link_to 'Destroy', budget, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Budget', new_budget_path %>

app/views/budgets/new.html.erb
<h1>New Budget</h1>

<%= render 'form' %>

<%= link_to 'Back', budgets_path %>

app/views/budgets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @budget.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @budget.description %>
</p>

<p>
  <strong>Starting Balance:</strong>
  <%= number_to_currency(@budget.balance) %>
</p>

<% if !@budget.entries.empty? %>
  <p>
  <strong>Entries:</strong>
  <% @budget.entries.each do |e| %>
    <p>
  	  Amount: <%= number_to_currency(e.amount) %><br />
	  Description: <%= e.description %><br />
	  Deductible?: <%= e.deductible %>
    </p>
  <% end %>
  </p>
<% end %>

<p>
  <strong>Running Balance:</strong>
  <%= number_to_currency(@budget.get_budget_total) %>
</p>

<hr>

<h2>Create a new entry for this budget</h2>
<%= render :partial => 'entries/shortform', :object => @entry %>

<hr>

<%= link_to 'Edit', edit_budget_path(@budget) %> |
<%= link_to 'Back', budgets_path %>

app/views/entries/_form.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :deductible %><br>
    <%= f.check_box :deductible %>
  </div>
  <div class="field">
    <%= f.label :budget_id %><br>
    <%= f.collection_select :budget_id, Budget.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/_shortform.html.erb
<%= form_for(@entry) do |f| %>
  <% if @entry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@entry.errors.count, "error") %> prohibited this entry from being saved:</h2>

      <ul>
      <% @entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amount %><br>
    <%= f.text_field :amount %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :deductible %><br>
    <%= f.check_box :deductible %>
  </div>
  <%= f.hidden_field :budget_id, :value => @budget.id %>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/entries/edit.html.erb
<h1>Editing Entry</h1>

<%= render 'form' %>

<%= link_to 'Show', @entry %> |
<%= link_to 'Back', entries_path %>

app/views/entries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Entries</h1>

<table>
  <thead>
    <tr>
      <th>Amount</th>
      <th>Description</th>
      <th>Deductible</th>
      <th>Assigned to Budget</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entries.each do |entry| %>
      <tr>
        <td><%= entry.amount %></td>
        <td><%= entry.description %></td>
        <td><%= entry.deductible %></td>
        <td><%= entry.budget.name %></td>
        <td><%= link_to 'Show', entry %></td>
        <td><%= link_to 'Edit', edit_entry_path(entry) %></td>
        <td><%= link_to 'Destroy', entry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Entry', new_entry_path %>

app/views/entries/new.html.erb
<h1>New Entry</h1>

<%= render 'form' %>

<%= link_to 'Back', entries_path %>

app/views/entries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amount:</strong>
  <%= @entry.amount %>
</p>

<p>
  <strong>Description:</strong>
  <%= @entry.description %>
</p>

<p>
  <strong>Deductible:</strong>
  <%= @entry.deductible %>
</p>

<%= link_to 'Edit', edit_entry_path(@entry) %> |
<%= link_to 'Back', entries_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Budgeter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>